### ISSUE TITLE
Can I get access to push here?

### ISSUE THREAD

**Issue by PjEdwards** [duckontheweb/sa-grid#1]
Hey Jon, we've got a demo coming up. Not a good long term solution, but while we work something out on NREL hardware I was wondering if I could have push access?

**Comment by duckontheweb** [comment]
Yeesh, I totally I forgot about this jenky setup...

I just added you as a collaborator, let me know if you have any trouble and we can figure out how to transfer this over to you or the NREL organization once you have some time.

**Comment by PjEdwards** [comment]
:) I went looking for the public deployment and was like "Whaa?" Hopefully they won't mind a change in URL so we can get it somewhere we control. Thanks for the invite!
